export const patients=[
    {   
        type:"Medical",
        img:"./Images/patient8.jpeg",
        index:1,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Sumit Singh",
       
    },
    {   
        type:"Medical",
        img:"./Images/patient2.jpg",
        index:2,
        purpose:"Save Us from bone Cancer By Providing..",
        organiser:"Rahul Jain",
    },
    {   
        type:"Medical",
        img:"./Images/patient9.jpeg",
        index:3,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Ritam Dutta",
    },
    {
        type:"Medical",
        img:"./Images/patient4.jpg",
        index:4,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Mohit Nimje",
    },
    {
        type:"Medical",
        img:"./Images/patient5.jpg",
        index:5,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Medical",
        img:"./Images/patient6.jpeg",
        index:6,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Medical",
        img:"./Images/patient7.jpeg",
        index:7,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Medical",
        img:"./Images/patient1.jpg",
        index:8,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Medical",
        img:"./Images/patient3.jpg",
        index:9,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Medical",
        img:"./Images/patient10.jpeg",
        index:10,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Hunger",
        img:"./Images/hunger1.jpeg",
        index:11,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Hunger",
        img:"./Images/hunger2.jpeg",
        index:12,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Hunger",
        img:"./Images/hunger3.jpeg",
        index:13,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Hunger",
        img:"./Images/hunger4.jpeg",
        index:14,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Hunger",
        img:"./Images/hunger5.jpeg",
        index:15,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Hunger",
        img:"./Images/hunger6.jpeg",
        index:16,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Hunger",
        img:"./Images/hunger7.jpeg",
        index:17,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Animal",
        img:"./Images/animal1.jpeg",
        index:18,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Animal",
        img:"./Images/animal2.jpeg",
        index:19,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Animal",
        img:"./Images/animal3.jpeg",
        index:20,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Animal",
        img:"./Images/animal4.jpeg",
        index:21,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Animal",
        img:"./Images/animal5.jpeg",
        index:22,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Environment",
        img:"./Images/env1.jpeg",
        index:23,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Environment",
        img:"./Images/env2.jpeg",
        index:24,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Environment",
        img:"./Images/env3.jpeg",
        index:25,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Environment",
        img:"./Images/env4.jpeg",
        index:26,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Environment",
        img:"./Images/env5.jpeg",
        index:27,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Environment",
        img:"./Images/env6.jpeg",
        index:28,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Environment",
        img:"./Images/env7.jpeg",
        index:29,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Women",
        img:"./Images/women1.jpeg",
        index:30,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Women",
        img:"./Images/women2.jpeg",
        index:31,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Women",
        img:"./Images/women3.jpeg",
        index:32,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Women",
        img:"./Images/women4.jpeg",
        index:33,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Memorial",
        img:"./Images/memorial1.jpeg",
        index:34,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Memorial",
        img:"./Images/memorial2.jpeg",
        index:35,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Memorial",
        img:"./Images/memorial3.jpeg",
        index:36,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Creative",
        img:"./Images/creative1.jpeg",
        index:37,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Creative",
        img:"./Images/creative2.jpeg",
        index:38,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Shivam Jaiswal",
    },
    {
        type:"Children",
        img:"./Images/children1.jpeg",
        index:39,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Sumit Singh",
    },
    {
        type:"Children",
        img:"./Images/children2.jpeg",
        index:40,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Sumit Singh",
    },
    {
        type:"Children",
        img:"./Images/children3.jpeg",
        index:41,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Sumit Singh",
    },
    {
        type:"Children",
        img:"./Images/children4.jpeg",
        index:42,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Sumit Singh",
    },
    {
        type:"Others",
        img:"./Images/other1.jpeg",
        index:43,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Sumit Singh",
    },
    {
        type:"Others",
        img:"./Images/other2.jpeg",
        index:44,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Sumit Singh",
    },
    {
        type:"Others",
        img:"./Images/other3.jpeg",
        index:45,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Sumit Singh",
    },
    {
        type:"Education",
        img:"./Images/education1.jpeg",
        index:46,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Sumit Singh",
    },
    {
        type:"Education",
        img:"./Images/education2.jpeg",
        index:47,
        purpose:"Save Our Premature Newborn Twins By Providing..",
        organiser:"Sumit Singh",
    },
]